// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9qkpkAp_yOjZpip8GC-FQd4mlqW9tmjg',
    appId: '1:37960151575:web:67b2130faaa917d790e252',
    messagingSenderId: '37960151575',
    projectId: 'books-c37ce',
    authDomain: 'books-c37ce.firebaseapp.com',
    storageBucket: 'books-c37ce.appspot.com',
    measurementId: 'G-56F933SDRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGORHUyZnuhn_EkQ_SENz5kw63PFOp6OY',
    appId: '1:37960151575:android:4ff54fcf7a417cf290e252',
    messagingSenderId: '37960151575',
    projectId: 'books-c37ce',
    storageBucket: 'books-c37ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonuwvMcVWcYaq4apsk2d0f5RukIrh61g',
    appId: '1:37960151575:ios:e90b50827bd8269690e252',
    messagingSenderId: '37960151575',
    projectId: 'books-c37ce',
    storageBucket: 'books-c37ce.appspot.com',
    iosBundleId: 'com.example.firebaseTut',
  );
}
